INCLUDE(FindPackageHandleStandardArgs)

macro(FIND_HERMES HERMES_LIBRARY DIRECTORY)
  FIND_LIBRARY(HERMES_COMMON_LIBRARY NAMES hermes_common hermes_common-debug PATHS DIRECTORY /usr/lib /usr/local/lib)
	FIND_PACKAGE_HANDLE_STANDARD_ARGS(HERMES_COMMON DEFAULT_MSG HERMES_COMMON_LIBRARY)
	
	if(HERMES_LIBRARY STREQUAL "HERMES2D")
		FIND_LIBRARY(HERMES2D_LIBRARY NAMES hermes2d hermes2d-debug PATHS DIRECTORY /usr/lib /usr/local/lib)
		FIND_PACKAGE_HANDLE_STANDARD_ARGS(HERMES DEFAULT_MSG HERMES2D_LIBRARY)
	endif(HERMES_LIBRARY STREQUAL "HERMES2D")
endmacro(FIND_HERMES HERMES_LIBRARY DIRECTORY)